order tests fix

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,54 +1,48 @@
 version: 2.1
-
-orbs:
-  java: circleci/openjdk@1.0
-
 jobs:
   build:
     docker:
-      - image: circleci/maven:3.6-jdk-11
+      - image: circleci/openjdk:8-jdk
 
     steps:
       - checkout
 
-      - restore_cache:
-          keys:
-            - v1-dependencies-{{ checksum "pom.xml" }}
+      # Set up your environment, install dependencies, etc.
+      # ...
 
       - run:
-          name: Build with Maven
-          command: mvn clean install
+          name: Build and test
+          command: mvn clean test
 
-      - save_cache:
-          paths:
-            - ~/.m2
-          key: v1-dependencies-{{ checksum "pom.xml" }}
-
-  test:
+  check_tests:
     docker:
-      - image: circleci/maven:3.6-jdk-11
+      - image: circleci/openjdk:8-jdk
 
     steps:
       - checkout
 
-      - restore_cache:
-          keys:
-            - v1-dependencies-{{ checksum "pom.xml" }}
+      # Set up your environment, install dependencies, etc.
+      # ...
+
+      - attach_workspace:
+          at: /tmp/workspace
 
       - run:
-          name: Run tests with Maven
-          command: mvn test
-
-      - save_cache:
-          paths:
-            - ~/.m2
-          key: v1-dependencies-{{ checksum "pom.xml" }}
+          name: Check test results
+          command: |
+            if [ -e "/tmp/workspace/target/surefire-reports/TEST-*.xml" ]; then
+              echo "All tests passed!"
+              exit 0
+            else
+              echo "Some tests failed or no test results found."
+              exit 1
+            fi
 
 workflows:
   version: 2
-  build-and-test:
+  build_and_check:
     jobs:
       - build
-      - test:
+      - check_tests:
           requires:
             - build
